### ISSUE TITLE
MirageOS support is broken

### ISSUE THREAD

**Issue by samoht** [inhabitedtype/bigstringaf#11]
See also https://github.com/janestreet/bin_prot/issues/19 and https://github.com/ocaml/dune/issues/783

- `PKG_CONFIG_PATH` is not set properly
- `jbuilder` has an issue with lazy loading of optional includes

**Comment by hannesm** [comment]
furthermore, at the time being, we need both `xen` and `freestanding` "cross-compilation" (which use slightly different C compiler flags, see ea2688225fa75d083cefc58e41bd259088b28588 as work-in-progress).. in the foreseeable future, the MirageOS `xen` backend will (hopefully) be rebased onto the freestanding effort (and thus no longer be needed).

**Comment by seliopou** [comment]
Thanks for the report, folks. I've just followed other examples I've found from other projects, so if you have a fix for this I'm very willing to merge it when it's ready.

**Comment by seliopou** [comment]
Fixed by #13.
