### ISSUE TITLE
Warning when compiling with js_of_ocaml

### ISSUE THREAD

**Issue by ghilesZ** [inhabitedtype/bigstringaf#26]
When compiling with js_of_ocaml, a warning is triggered: 
`free variables in primitive code "bigstringaf_memcmp_bigstring (/patho/to/.opam/4.07.0/lib/bigstringaf/runtime.js:57)`

Which is maybe(probably?) due to the typos `//Requres` instead of `//Requires` line 59 and 69 of the file runtime.js: https://github.com/inhabitedtype/bigstringaf/blob/master/lib/runtime.js#L59

**Comment by seliopou** [comment]
I could have sworn that all the JSoO issues had been resolved, but maybe something was lost in the shuffle while moving this code out of angstrom and/or faraday. If you have a confirmed fix, I'd happily accept a PR. Otherwise, I'll get to it this weekend.

**Comment by ghilesZ** [comment]
Pull requested (or is it Request pulled?). It's a 2-Characters change, but still twice as big as my shortest ever :)

**Comment by seliopou** [comment]
There’s no jsoo CI setup yet. You confirmed it works on your end?

**Comment by ghilesZ** [comment]
Yes it works

**Comment by seliopou** [comment]
Fixed by #28.
