### ISSUE TITLE
Implement `add` function[s]

### ISSUE THREAD

**Issue by XVilka** [inhabitedtype/bigstringaf#43]
Something like `Buffer.add_bytes` but for Bigarray.
```ocaml
val add: ~out:t -> t -> unit
```
Maybe also the similar functions but from bytes and string, to be consistent with `blit` functions.

**Comment by seliopou** [comment]
The purpose of bigstringaf is to expose efficient versions of bigstring intrinsics and stubs. Everything that can be built on top of those is considered out of scope, but could go into a separate library.

Though FYI, there is a module in core_kernel called [`Bigbuffer`](https://ocaml.janestreet.com/ocaml-core/latest/doc/core_kernel/Core_kernel/Bigbuffer/index.html) that implements something close to the `Buffer` interface but backed by a  `Bigstring.t`. There is also base_bigstring which exposes a [`concat`](https://github.com/janestreet/base_bigstring/blob/master/src/base_bigstring.mli#L66-L67) operation, which may be what you're looking for.
