### ISSUE TITLE
Cannot install on Windows 7 x64 bit

### ISSUE THREAD

**Issue by PavelKotov1** [inhabitedtype/bigstringaf#44]
Hello, dear friends!
Please help to figure out what i am doing wrong here:

$ opam install bigstringaf
The following actions will be performed:
  - install bigstringaf 0.6.1

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><>
[bigstringaf.0.6.1] found in cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><>
[ERROR] The compilation of bigstringaf failed at "D:\\cygwin64\\home\\root\\OCaml64\\home\\root\\.opam\\ocaml-variants.4.08.0+mingw64c\\bin\\dune.exe build -p bigstringaf -j 7".

#=== ERROR while compiling bigstringaf.0.6.1 ==================================#
# context     2.0.6 | win32/x86_64 | ocaml-variants.4.07.1+msvc64c | git+https://github.com/fdopen/opam-repository-mingw.git#opam2
# path        ~/.opam/ocaml-variants.4.08.0+mingw64c/.opam-switch/build/bigstringaf.0.6.1
# command     D:\cygwin64\home\root\OCaml64\home\root\.opam\ocaml-variants.4.08.0+mingw64c\bin\dune.exe build -p bigstringaf -j 7
# exit-code   1
# env-file    ~/.opam/log/bigstringaf-5708-42bb52.env
# output-file ~/.opam/log/bigstringaf-5708-42bb52.out
### output ###
#       ocamlc lib/bigstringaf_stubs.obj (exit 2)
# (cd _build/default/lib && D:\cygwin64\home\root\OCaml64\home\root\.opam\ocaml-variants.4.08.0+mingw64c\bin\ocamlc.opt.exe -g -I D:\cygwin64\home\root\OCaml64\home\root\.opam\ocaml-variants.4.08.0+mingw64c\lib\bigarray-compat -ccopt -nologo -ccopt -O2 -ccopt -Gy- -ccopt -MD -ccopt -Wall -ccopt -Wextra -ccopt -Wpedantic -o bigstringaf_stubs.obj bigstringaf_stubs.c)
# cl : Command line error D8021 : invalid numeric argument '/Wextra'

<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
+- The following actions failed
| - build bigstringaf 0.6.1
+-
- No changes have been performed

**Comment by seliopou** [comment]
I would've thought these flags would work on Windows.

@dra27 a penny for your thoughts?

**Comment by dra27** [comment]
@seliopou - cl doesn’t support GCC’s warnings flags

**Comment by PavelKotov1** [comment]
Somehow same thing worked on Windows 10 and i am happy since it was not really important which OS to use as long as i have working installation.
Thanks everybody!
